name: Parent Issue Template
description: Create a parent issue, which will automatically create sub-issues.
title: "%a parent issue title%"
labels: 
- "automation:create:subissues"
- "parent:myparent"
projects: 
- "goldberc/1"
assignees:
  - crlgb
body:
  - type: markdown
    attributes:
      value: |
        This is a parent issue template. It will automatically create sub-issues for you.